# Site settings
title: "code.code.org: The Code.org Developer Blog"
email: support@code.org
description: >
  The developer blog from the engineering team at <a href="https://code.org/">Code.org</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code-dot-org.github.io" # the base hostname & protocol for your site
twitter_username: codeorg
github_username:  code-dot-org

# Build settings
markdown: kramdown
kramdown:
  input: GFM
